### ISSUE TITLE
Milestone 1 Build Review

### ISSUE THREAD

**Issue by verdayne** [Damgt-Studios/GolemGame#17]
- [x] Game Loop
- [x] UI: Debug information is allowed
- [x] Audio: SFX and Looping Track
- [x] Input: Keyboard/Mouse, Controller
- [x] Game World: Static mesh with texture
- [x] Basic Mechanics
- [x] Asset Pipeline: From creation to integration
- [x] Functional main menu
- [x] Game end-state goes back to menu
- [x] Fullscreen release support
- [x] Feedback: Debug text is allowed
